### ISSUE TITLE
google search bug

### ISSUE THREAD

**Issue by onthebreeze** [edi3/edi3.github.io#14]
When using the search tool, I get an error page:

<img width="1680" alt="Screen Shot 2020-02-21 at 7 42 56 am" src="https://user-images.githubusercontent.com/13426392/74976981-e8b45900-547d-11ea-9cd4-da4b94a96386.png">

maybe needs a new api key - perhaps usage limits reached?

**Comment by kshychko** [comment]
@onthebreeze , I wasn't able to reproduce the issue, tried three different browsers. Could you please try again?

**Comment by onthebreeze** [comment]
Strange - now it works ok
