### ISSUE TITLE
pandoc for github markdown -> MS word conversion

### ISSUE THREAD

**Issue by onthebreeze** [edi3/edi3.github.io#15]
Need to generate word documents from edi3.org specification pages such as https://edi3.org/specs/edi3-notary/develop/

please setup a pandoc or similar capability to make this simple.

**Comment by kshychko** [comment]
@onthebreeze , please check out https://edi3.org/specs/edi3-notary/develop/
Do we need to apply any styles to a generated doc file?

**Comment by kshychko** [comment]
Closing the issue as implemented.
